#!/usr/bin/env bash
# Automatizing the nginx configuration for my servers
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "15i \\\tadd_header X-Served-By 122394-web-01;" /etc/nginx/nginx.conf
sudo service nginx restart
